server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db-quantitative-financ-db
    username: administrator
    password: 1234
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    tags-sorter: alpha

